--CREATING AISLE TABLE
CREATE TABLE aisle(
   aisle_id INT PRIMARY KEY,
   aisle VARCHAR(50)
);
 
--CREATING DEPARTMENT TABLE
CREATE TABLE departments(
  department_id INT PRIMARY KEY,
  department VARCHAR(30)
);

 
--CREATING PRODUCT TABLE
CREATE TABLE products_table(
  product_id INT PRIMARY KEY,
  product_name VARCHAR(150),
  aisle_id INT REFERENCES aisle(aisle_id),
  department_id INT REFERENCES departments(department_id),
  unit_cost NUMERIC(10,2),
  unit_price NUMERIC(10,2)
);

 --CREATING ORDERS TABLE
CREATE TABLE orders_table(
  order_id INT PRIMARY KEY,
  user_id INT,
  product_id INT REFERENCES products_table(product_id),
  quantity INT,
  order_date DATE,
  order_dow INT,
  order_hour_of_day INT,
  day_since_prior_order INT,
  order_status VARCHAR(20)
);


--correcting product name data type
ALTER TABLE products_table
ALTER COLUMN product_name TYPE VARCHAR (400);


--QUESTIONS
--1)What are the top selling products by revenue and how much 
--revenue have the generated?
SELECT  p.product_name,
     '$ ' || SUM(o.quantity * p.unit_price) AS Total_revenue
FROM products_table AS P
INNER JOIN orders_table AS o ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY SUM(o.quantity * p.unit_price) DESC
LIMIT 10;


--2)On which day of the week are chocolates most sold?
SELECT  o.order_dow,
       COUNT(order_id) AS no_of_orders,
	   CASE
	   WHEN o.order_dow = 0 THEN 'Sunday'  
	   WHEN o.order_dow = 1 THEN 'Monday'
	   WHEN o.order_dow = 2 THEN 'Tuesday'
	   WHEN o.order_dow = 3 THEN 'Wednesday'
	   WHEN o.order_dow = 4 THEN 'Thursday'
	   WHEN o.order_dow = 5 THEN 'Friday' 
	   ELSE 'Saturday'
	   END AS days_of_week
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
WHERE p.product_name  ILIKE '%Chocolate%'
GROUP BY o.order_dow
ORDER BY no_of_orders DESC
LIMIT 1;
INSIGHT; Chocolates are sold mostly on Sundays


--3)do we have any department where we have over $15million in revenue 
--and what is the profit?
SELECT d.department,
  '$' || SUM(p.unit_price * o.quantity) AS Total_reveue,
 '$' || SUM((p.unit_price - p.unit_cost) * o.quantity) AS Profit
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
INNER JOIN departments AS d ON d.department_id = p.department_id
GROUP BY d.department
HAVING SUM (o.quantity * p.unit_price) > 15000000 ;

--4)IS it true customers buy more alcoholic products on xmas day 2019?
SELECT d.department,
      COUNT (d.department_id) AS no_of_patronage,
	'$' ||   SUM(p.unit_price * o.quantity) AS Total_revenue
FROM departments AS d
INNER JOIN products_table AS p ON p.department_id = d.department_id
INNER JOIN orders_table AS o  ON o.product_id = p.product_id
WHERE o.order_date = '2019-12-25'
GROUP BY d.department
ORDER BY no_of_patronage DESC;



--5)Which year did Instacart generate the most profit?
SELECT EXTRACT(YEAR FROM order_date) AS Years,
 '$' || SUM((p.unit_price - p.unit_cost) * o.quantity) AS PROFIT
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
GROUP BY  EXTRACT(YEAR FROM order_date)
ORDER BY SUM((p.unit_price - p.unit_cost) * o.quantity) DESC
LIMIT 1;

--6)How long has it been since the last cheese order?
SELECT (CURRENT_DATE - MAX(order_date)) || ' days' AS period
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
INNER JOIN aisle AS a ON a.aisle_id = p.aisle_id 
WHERE a.aisle_id = '2'; 
INSIGHT; The last cheese order was made over a year ago   

--7)What time of the day do sell alcohols the most?
SELECT o.order_hour_of_day,
     COUNT(p.department_id) AS no_of_patronage
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
INNER JOIN departments AS d on d.department_id = p.department_id 
WHERE d.department ='alcohol'
GROUP BY o.order_hour_of_day
ORDER BY no_of_patronage DESC
LIMIT 1;


--8)what is the total revenue generated in Qtr 2 and Qtr 3 of 2016 from breads
SELECT  '$' || SUM (p.unit_price * o.quantity) AS Total_revenue
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
WHERE product_name ILIKE '%breads%' 
         AND order_date BETWEEN '2016-04-01' AND '2016-10-31';
		 
		 
--9)Which 3 products do people buy at night(2020-2022)
SELECT p.product_name,
        COUNT (order_id) AS no_of_orders
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
WHERE  o.order_date BETWEEN '2020-01-01' AND '2022-12-31' 
      AND o.order_hour_of_day IN ('18','19','20','21','22','23','0','1','2','3','4','5')	
GROUP BY p.product_name
ORDER BY no_of_orders DESC
LIMIT 3;

--10)What is the total revenue generated by juice products?
SELECT  '$' || SUM (p.unit_price * o.quantity) AS Total_revenue
FROM orders_table AS o
INNER JOIN products_table AS p ON p.product_id = o.product_id
WHERE p.product_name ILIKE '%Juice%';
